### ISSUE TITLE
Inject speedbump in a specific paragraph

### ISSUE THREAD

**Issue by noppanit** [fusioneng/speed-bumps#15]
We have a requirement to inject recirc module in a specific paragraph. 

https://trello.com/c/Vr364ijY/156-speedbump-recirc

**Comment by danielbachhuber** [comment]
Isn't this a theme integration issue?

**Comment by noppanit** [comment]
I thought we should be able to use Speed bump to insert the recirc module but we will have a filter to insert to a specific paragraph?

**Comment by noppanit** [comment]
Not needed right now.
