### ISSUE TITLE
Speed bump gets inserted twice

### ISSUE THREAD

**Issue by noppanit** [fusioneng/speed-bumps#19]
There's a bug where speed bumps get inserted more than once. 

![screenshot 2015-06-18 16 31 31](https://cloud.githubusercontent.com/assets/638379/8242714/5b2f8c94-15df-11e5-8c8f-0ae9496037b2.png)

**Comment by taterread** [comment]
You say bug? I say feature. If we insert it twice, it'll seem like we mean
it. People will respect us more.

:-)


On Thu, Jun 18, 2015 at 5:28 PM, Noppanit Charassinvichai <
notifications@github.com> wrote:

> There's a bug where speed bumps get inserted more than once.
>
> [image: screenshot 2015-06-18 16 31 31]
> <https://cloud.githubusercontent.com/assets/638379/8242714/5b2f8c94-15df-11e5-8c8f-0ae9496037b2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fusioneng/speed-bumps/issues/19>.
>



-- 
 *tater read*
Senior UX Designer
tater.read@fusion.net
*m. *(646) 479-1424

 <http://fusion.net> <http://fusion.net>



 <http://fusion.net>
