### ISSUE TITLE
Rename `is_ad_already_inserted_here` method

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/speed-bumps#22]
It should be `is_speed_bump`_already_inserted_here()` or similar

**Comment by goldenapples** [comment]
Also, all of our methods are currently named backwards. `is_speed_bump_already_inserted_here()` returns false if the speed bump is inserted there. It should be something like `check_no_speed_bump_inserted_here()`. Language is confusing.

**Comment by noppanit** [comment]
Closing in favour of #20
