### ISSUE TITLE
Define structure for `register_speed_bump()` args

### ISSUE THREAD

**Issue by goldenapples** [fusioneng/speed-bumps#36]
The set of options available has grown organically so far, leading to a somewhat inconsistant set of options available:

```
'minimum_content_length' => 1200,
'paragraph_offset' => 0,
'element_constraints' => array(
    'iframe',
    'oembed',
    'image',
    ),
'minimum_space_from_other_inserts' => 1,
'minimum_space_from_other_inserts_words' => null,
'minimum_words_from_end' => null,
'minimum_paragraphs_from_end' => null,
```

I think this API could be cleaned up so that the options available are much more intuitive.

Defining a nested array of options that looks more like

```
''global_constraints' => array(
    'content_length' => (
        'chars' => 1200,
        'paras' => 8,
        'words' => 800
        ),
'from_start' => array(
    'paras' => 4,
    'words' => 75,
    'chars' => 300
),
'from_end' => array(
    'paras' => 2,
    'words' => 75,
    'chars' => 300
),
'from_element' => array(
    'iframe' => 1,
    'oembed' => 1,
    'image' => array(
        'before' => 2,
        'after' => 1
    ),
),
'from_speedbump' => array(
    'paras' => 3,
    'words' => 75,
    'chars' => 300
),
```

would make the plugin much more approachable.

Some concerns are:

- [x] defining a way to inherit defaults, as `wp_parse_args` doesn't work recursively through nested arrays.
- [ ] making sure not to break existing behavior we're depending on for our theme, or at least deploying theme changes in tandem with plugin changes.

**Comment by danielbachhuber** [comment]
:100:
