### ISSUE TITLE
Performance for using Speed Bumps in post content

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/speed-bumps#37]
Because we're using regex on blob content, we should do a little bit of testing to determine the performance impact of using Speed Bumps in post content

**Comment by goldenapples** [comment]
Comparing performance before and after #59:

Time of tests in `Test_Speed_Bumps_Element_Constraints_Definitions`:

Test | Before #59 | After #59
----- | --------- | -----------
test_if_the_paragraph_has_blockquote() | 0.006925106048584 | 0.0025269985198975
test_if_the_paragraph_has_image() | 0.0028619766235352 | 0.0013930797576904
test_if_the_paragraph_has_iframe() | 0.0024020671844482 | 0.0011229515075684
test_if_the_paragraph_has_shortcode() | 0.0031769275665283 | 0.0014858245849609
test_if_the_paragraph_has_twitter() | 1.5223741531372 | 0.0098981857299805
test_if_the_paragraph_has_video() | 0.34060502052307 | 0.0011491775512695
test_if_the_paragraph_has_vine() | 0.82086682319641 | 0.0013828277587891
test_if_the_paragraph_has_h1() | 0.011261940002441 | 0.01052188873291
test_if_the_paragraph_has_h6() | 0.0012571811676025 | 0.0010430812835693
test_if_the_paragraph_has_header() | 0.0010440349578857 | 0.00063610076904297
