### ISSUE TITLE
Pass some context into the speed bump callback function

### ISSUE THREAD

**Issue by goldenapples** [fusioneng/speed-bumps#44]
It would be great if a speed bump could modify its output in some ways based on where in the content it was being output, or what other insertions have happened in the context, or even the text of the surrounding paragraphs.

To make this possible, the `string_to_inject` callback function could receive some relevant context as parameters. Passing `$context` and `$already_inserted` into it should enable most conceivable use cases.

**Comment by danielbachhuber** [comment]
What would the named `$context`s be?

**Comment by goldenapples** [comment]
We have a couple variables defined already, which provide most of the context we need:

[`$context`](https://github.com/fusioneng/speed-bumps/blob/master/speed-bumps.php#L103-L110) and [`$already_inserted`](https://github.com/fusioneng/speed-bumps/blob/master/speed-bumps.php#L123-L126). Between those two arrays, I think a speed bump should have enough information to do basic things like changing its output based on what paragraph in an article it's being displayed or what they surrounding text is...

**Comment by goldenapples** [comment]
Actually the callback was already getting `$context` passed into it as an argument. Added the array of other speed bumps into the arguments in #45.

**Comment by noppanit** [comment]
@goldenapples I think this issue has been addressed already? Should we close?

**Comment by noppanit** [comment]
@goldenapples can I close this issue?

**Comment by goldenapples** [comment]
Yup, its been addressed and merged

**Comment by noppanit** [comment]
Thanks. Closing as #45 is merged
