### ISSUE TITLE
Polar ad slot rendering too close to beginning of post

### ISSUE THREAD

**Issue by kkropski** [fusioneng/speed-bumps#49]
Should never render < 600 characters from the start of a post, original list of rules here: https://docs.google.com/spreadsheets/d/1ht0TlRoBgUiii2Wq-pbJfCdaSr-ClLhIWVhnGeQSOLY/edit#gid=1314778934

Examples:
http://fusion.net/story/166806/the-best-way-to-solve-homelessness-is-giving-people-permanent-housing-major-study-finds/

http://fusion.net/story/117767/a-complete-guide-to-flakka-the-horrible-street-drug-terrorizing-south-florida/

http://fusion.net/story/61899/he-served-20-years-for-a-crime-he-didnt-commit-and-then-27-more-hours-for-a-broken-sink/

Related: https://github.com/fusioneng/fusion-theme/issues/2701

**Comment by danielbachhuber** [comment]
Moving this to the theme https://github.com/fusioneng/fusion-theme/issues/3495
