### ISSUE TITLE
Speedbump Shouldn't Render > 300 characters after inline element + before end of article

### ISSUE THREAD

**Issue by kkropski** [fusioneng/speed-bumps#5]
http://wp.fusion.net/staging/story/99903/mario-balotelli-racism-salvini-muntari/

In this case, no inline element should render on this post at all because 

* [x] there's less than 300 characters before the speed bump

![screen shot 2015-05-15 at 6 30 04 pm](https://cloud.githubusercontent.com/assets/7570776/7663018/f2cae756-fb31-11e4-9393-56c6d6cd0c0a.png)

* [x] there's less than 600 characters before the end of the article

![screen shot 2015-05-15 at 6 30 15 pm](https://cloud.githubusercontent.com/assets/7570776/7663021/fcbfb552-fb31-11e4-8ebc-9569cd11ac2f.png)

**Comment by noppanit** [comment]
@kkropski This is merged already. Can you verify and close the issue please?

**Comment by kkropski** [comment]
@noppanit looks good - the staging link above now seems to adhere to the rules (more than 300 characters between element and speedbump)
