### ISSUE TITLE
Polar unit rendering after <big> tag

### ISSUE THREAD

**Issue by kkropski** [fusioneng/speed-bumps#50]
Editor used `<big><strong>` as a header in stead of an `<h2>`, and since it's not a typical ordered list or bulleted list, the rule didn't apply here:

Link: http://fusion.net/story/167128/watch-new-footage-of-mexican-drug-lord-el-chapo-moments-before-he-escaped-from-prison/

![screen shot 2015-07-15 at 11 20 08 am](https://cloud.githubusercontent.com/assets/7570776/8702203/61b4a148-2ae4-11e5-8afe-42b2195daba4.png)

![screen shot 2015-07-15 at 11 22 52 am](https://cloud.githubusercontent.com/assets/7570776/8702209/673ca912-2ae4-11e5-9fe9-33f267a98720.png)

In this case, a 600 character rule would probably have prevented the Polar ad from being pushed to the bottom of the post

**Comment by noppanit** [comment]
@kkropski You mean a rule that speed bump should be inserted after a paragraph with less than 600 characters?

**Comment by kkropski** [comment]
> You mean a rule that speed bump should be inserted after a paragraph with less than 600 characters?

@noppanit I meant that if the 600 character rule existed, this would have been placed after paragraph 2 and not been forced to the bottom. Nevertheless, if editorial is going to use the `<big>` tag, then we should probably write a rule to prevent speedbump from rendering right after a line with `<big>`

Actually gonna close this in favor of https://github.com/fusioneng/fusion-theme/issues/3496 where I've added this as an added req to the list
