### ISSUE TITLE
Off-by-one error in "from_start" and "from_end" arguments

### ISSUE THREAD

**Issue by goldenapples** [fusioneng/speed-bumps#60]
An off-by-one error in the `array_slice` call used in the `Text::meets_minimum_distance_from_start` and `Text::meets_minimum_distance_from_end` constraints means that speed bumps are being blocked from insertion too far from the start and end of articles.

For example the default argument of `'from_start' => array( 'paragraphs' => 3 )` will result in the first speed bump being inserted after the fourth paragraph (based on an array_slice between `( 0, 3 )`) rather than the third as expected.

Reported here: https://github.com/fusioneng/speed-bumps/pull/54#issuecomment-123042327

This is a specific problem of the more general confusion described in #52. But it should probably fixed first so that current behavior works as expected.

**Comment by danielbachhuber** [comment]
:ship:
