### ISSUE TITLE
Use `$wp_oembed->get_provider` for the purposes of oembed detection

### ISSUE THREAD

**Issue by goldenapples** [fusioneng/speed-bumps#62]
Since the check for an oembed is only concerned with whether or not an oembed exists, and not the actual output of the embed, it is more efficient to just use the `WP_oEmbed->get_provider()` method, which just validates that a url is valid for a provider, and doesn't actually query the provider or call the callback defined to process markup.

See #59 and https://github.com/fusioneng/speed-bumps/issues/37.

**Comment by goldenapples** [comment]
Performance difference is about 50% faster per check:

Provider | Before | After 
----- | --------- | -----------
twitter | 0.0098981857299805 | 0.0049540996551514
youtube | 0.0011491775512695 | 0.00016212463378906
vine | 0.0013828277587891 | 0.00028514862060547

@danielbachhuber only problem is that the `class-oembed.php` file isn't autoloaded where we need it to be, making this ugly `require_once` necessary. Do you have thoughts on this?

**Comment by danielbachhuber** [comment]
:ship:
