### ISSUE TITLE
Ad Hierarchy bug 

### ISSUE THREAD

**Issue by mkeppel** [fusioneng/speed-bumps#64]
I am noticing on a few different posts that our established hierarchy is not being upheld. 

We are supposed to show speedbump elemnts in this order Polar, Teads, then inline related article recirculation. The post below shows Recirc and then Polar: http://fusion.net/story/170375/sandra-bland-prosecutor-accused-of-racism/

![screen shot 2015-07-21 at 5 52 05 pm](https://cloud.githubusercontent.com/assets/7562729/8813273/2cefbd62-2fd0-11e5-8a45-e4f02d116676.png)

**Comment by goldenapples** [comment]
Closing this issue, as the problem was theme-specific and tracked in https://github.com/fusioneng/fusion-theme/issues/3548.
