### ISSUE TITLE
Speedbump Injected into a block quote

### ISSUE THREAD

**Issue by mkeppel** [fusioneng/speed-bumps#65]
On this post: http://fusion.net/story/170375/sandra-bland-prosecutor-accused-of-racism/ 
our polar campaign is injected into a block
![screen shot 2015-07-21 at 5 55 33 pm](https://cloud.githubusercontent.com/assets/7562729/8813324/9545d3ce-2fd0-11e5-979e-48202d8d7586.png)
 quote when it should be avoiding block quotes.

**Comment by danielbachhuber** [comment]
This is already tracked by #6
