### ISSUE TITLE
Autoload classes. 

### ISSUE THREAD

**Issue by anthony2727** [fusioneng/speed-bumps#9]
When PHP 5.x came to life, many improvements like: namespaces and autoloading became really important features when producing more elegant and efficient code. 

Here I propose the implementation of an autoload approach for loading any class-dependent file at any class instantiation time. e.g: $foo = new Namespace\Foo. Here we're taking advantage of the Namespace capability and the ```spl_autoload_register()```function, so no include() or require() declaration will be necessary before any of these class instantiation. (There're many other advantages like: Name Collision Prevention when different plugins are sharing the same name -this is prevented by namespace enforcement specifically). 

The propose will be produced following the [WP Naming Convention] (https://make.wordpress.org/core/handbook/coding-standards/php/#naming-conventions)

**Comment by noppanit** [comment]
Closing in favour of #12
